### ISSUE TITLE
AppointmentViewing refactoring

### ISSUE THREAD

**Issue by Skaurm** [CSC207-UofT/course-project-git-good-was-taken#67]
This use case's name is deceptive because it either returns the details for an Appointment (that hasn't occured yet) or the details of a past VaccinationRecord (has already occured). But, not all Vaccination records came from Appointments (e.g. Walk ins).

**Currently, this use case provides details for the following cases:**
1. Appointment Instances
2. VaccinationRecord Instances which were originally Appointments
3. VaccinationRecord Instances which were for walk-in (not bookable)

**Possible Solutions:**
1. Rename the Use Case to something more general, like "DetailsViewing"
2. Separate this into two use cases: "AppointmentViewing" and "VaccinationLogViewing"

**Related discussion:** When an Appointment is turned into a VaccinationRecord, the new ID for this record (String) is A + the appointment ID (integer). Similarly, if a walk-in vaccination is recorded in Vaccination Record, the new ID for this record (String) is V + the ID (integer) provided by the user. The reasoning for this was to make sure that all IDs are unique. Is this approach good for now?

**Comment by shayaanmk** [comment]
The only case I believe that we should take into account is a booked appointment that has not yet occurred. There really isn't any reason to view the details of a previous appointment.
